name: Actualizar podcasts

on:
  workflow_dispatch:

  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm ci

      - name: Actualizar episodios
        run: node scripts/update.js

      - name: Commit y Push si hay cambios
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "Actualización automática"
            git push
          else
            echo "No hay cambios"
          fi
